image: monachus/hugo

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - publish

cache:
  # Required to keep artifacts from old builds, e.g. from master
  paths:
    - public
    - public/tags
    - public/cv
    - public/page
    - public/post

pages:
  stage: publish
  script:
    - dir="$CI_COMMIT_REF_SLUG"
    - if [ "$CI_COMMIT_REF_SLUG" == "$CI_DEFAULT_BRANCH" ]; then dir=""; fi;
    - dir="public/$dir"
    - echo "Deploying to $dir"
    - hugo -d $dir
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
      - public
    expire_in: 5 days
  when: always

# letsencrypt-renewal:
#   only:
#     - schedules
#   variables:
#     CERTBOT_RENEWAL_PIPELINE_GIT_TOKEN: $CERTBOT_RENEWAL_PIPELINE_GIT_TOKEN
#   script:
#     - echo "deb http://ftp.debian.org/debian jessie-backports main" >> /etc/apt/sources.list
#     - apt-get update
#     - apt-get install certbot -t jessie-backports -y
#     - export PATH=$PATH:$CI_PROJECT_DIR
#     - git config --global user.name $GITLAB_USER_LOGIN
#     - git config --global user.email $GITLAB_USER_EMAIL
#     - ./letsencrypt_generate.sh
