baseurl = "https://trile.dev"
DefaultContentLanguage = "en"
title = "MỌT coder"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
disqusShortname = "trile-dev"
googleAnalytics = "UA-135463702-1"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
canonifyurls  = true
enableGitInfo = true

[Params]
#   homeTitle = "MỌT coder" # Set a different text for the header on the home page
#   subtitle = "Đây là blog cá nhân của một MỌT coder"
  logo = "img/trile-avatar.jpg" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "2006/01/02"
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
  commit = "gitlab.com/thanhtrixx/thanhtrixx.gitlab.io/commit/"

#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Tri Le"
  website = "trile.dev"
  email = "thanhtrixx@gmail.com"
  facebook = "thanhtrixx"
  gitlab = "thanhtrixx"
  linkedin = "tri-le-19a06aab"
  github = "thanhtrixx"
#   bitbucket = "username"
#   twitter = "username"
#   reddit = "username"
#   xing = "username"
#   stackoverflow = "users/XXXXXXX/username"
#   snapchat = "username"
#   instagram = "username"
#   youtube = "user/username" # or channel/channelname
#   soundcloud = "username"
#   spotify = "username"
#   bandcamp = "username"
#   itchio = "username"
#   vk = "username"
#   paypal = "username"
#   telegram = "username"
#   500px = "username"

# [[menu.main]]
#     name = "Blog"
#     url = ""
#     weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

# [[menu.main]]
#     identifier = "samples"
#     name = "Samples"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Big Image Sample"
#     url = "post/2017-03-07-bigimg-sample"
#     weight = 1

# [[menu.main]]
#     parent = "samples"
#     name = "Math Sample"
#     url = "post/2017-03-05-math-sample"
#     weight = 2

# [[menu.main]]
#     parent = "samples"
#     name = "Code Sample"
#     url = "post/2016-03-08-code-sample"
#     weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3