baseURL = "https://thanhtrixx.gitlab.io/blog/"
languageCode = "vi"
title = "Vì CODE"
theme = "hyde-hyde"
# googleAnalytics = "your-google-analytics-id"
enableRobotsTXT = true
publishDir = "blog"

[params]
  author = "Author"
  description= "Blog của 1 anh mọt code"
  themeColor = "theme-base-0d"
  layoutReverse = true
  GraphCommentId = "V-Code"


[[menu.main]]
    name = "Home" 
    weight = 1
    url = "/" #URL address
[[menu.main]]
    name = "Bài viết"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "Youtube"
    weight = 3
    url = "/chuyen-code/"
[[menu.main]]
    name = "Facebook"
    weight = 4
    url = "/chuyen-code/"
[[menu.main]]
    name = "Giới thiệu"
    weight = 5
    url = "/gioi-thieu/"

