baseURL = "https://thanhtrixx.gitlab.io"
languageCode = "vi"
title = "Vì CODE"
theme = "hyde-hyde"
googleAnalytics = "UA-135463702-1"
enableRobotsTXT = true

[params]
  author = "Author"
  description= "Blog của 1 anh mọt code"
  themeColor = "theme-base-0d"
  layoutReverse = true
  GraphCommentId = "V-Code"


[[menu.main]]
    name = "Home" 
    weight = 1
    url = "/" #URL address
[[menu.main]]
    name = "Bài viết"
    weight = 2
    url = "/posts/"
[[menu.main]]
    name = "Youtube"
    weight = 3
    url = "https://www.youtube.com/channel/UCVYtyut3pjXVO54nx2mCG0Q?view_as=subscriber"
[[menu.main]]
    name = "Facebook"
    weight = 4
    url = "https://www.facebook.com/thanhtrixx"
[[menu.main]]
    name = "Giới thiệu"
    weight = 5
    url = "/gioi-thieu/"

